In [237]:
import pandas as pd

In [238]:
home_spending = pd.read_csv(r"C:/Downloads/new_data/Chi tiêu tiêu dùng cuối cùng hàng năm của hộ gia đình theo mục đích (COICOP).csv")
eu_regions = pd.read_csv(r"C:/Downloads/new_data/eu_country.csv")
home_spending.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,FREQ,Fréquence d'observation,REF_AREA,Zone de référence,SECTOR,Secteur institutionnel,...,CONF_STATUS,Statut de confidentialité,DECIMALS,Décimales,OBS_STATUS,Statut d'observation,UNIT_MULT,Multiplicateur d'unité,CURRENCY,Monnaie
0,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN10@DF_TABLE5_T501(1.0),Dépenses annuelles de consommation finale des ...,I,A,Annuelle,FRA,France,S14,Ménages,...,F,Libre (libre pour publication),1,One,A,Valeur normale,6,Millions,EUR,Euro
1,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN10@DF_TABLE5_T501(1.0),Dépenses annuelles de consommation finale des ...,I,A,Annuelle,FRA,France,S14,Ménages,...,F,Libre (libre pour publication),1,One,A,Valeur normale,6,Millions,EUR,Euro
2,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN10@DF_TABLE5_T501(1.0),Dépenses annuelles de consommation finale des ...,I,A,Annuelle,FRA,France,S14,Ménages,...,F,Libre (libre pour publication),1,One,A,Valeur normale,6,Millions,EUR,Euro
3,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN10@DF_TABLE5_T501(1.0),Dépenses annuelles de consommation finale des ...,I,A,Annuelle,FRA,France,S14,Ménages,...,F,Libre (libre pour publication),1,One,A,Valeur normale,6,Millions,EUR,Euro
4,DATAFLOW,OECD.SDD.NAD:DSD_NAMAIN10@DF_TABLE5_T501(1.0),Dépenses annuelles de consommation finale des ...,I,A,Annuelle,FRA,France,S14,Ménages,...,F,Libre (libre pour publication),1,One,A,Valeur normale,6,Millions,EUR,Euro

In [239]:
home_spending.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'ACTION', 'FREQ',
       'Fréquence d'observation', 'REF_AREA', 'Zone de référence', 'SECTOR',
       'Secteur institutionnel', 'COUNTERPART_SECTOR',
       'Secteur institutionnel de contrepartie', 'TRANSACTION', 'Transaction',
       'INSTR_ASSET', 'Instruments financiers et actifs non financiers',
       'ACTIVITY', 'Activité économique', 'EXPENDITURE', 'Dépense',
       'UNIT_MEASURE', 'Unité de mesure', 'PRICE_BASE', 'Type de prix',
       'TRANSFORMATION', 'Transformation', 'TABLE_IDENTIFIER',
       'Identifiant de tableau', 'TIME_PERIOD', 'Période temporelle',
       'OBS_VALUE', 'Valeur d'observation', 'REF_YEAR_PRICE',
       'Prix ​​année de référence', 'CONF_STATUS', 'Statut de confidentialité',
       'DECIMALS', 'Décimales', 'OBS_STATUS', 'Statut d'observation',
       'UNIT_MULT', 'Multiplicateur d'unité', 'CURRENCY', 'Monnaie'],
      dtype='object')

In [240]:
cols_keep = [
    "TIME_PERIOD",          # năm
    "REF_AREA",             # mã quốc gia
    "Zone de référence",    # tên quốc gia      
    "Dépense",              #Tên đầy đủ của loại chi tiêu    
    "OBS_VALUE",             
    "UNIT_MULT",
    "CURRENCY"
]

In [241]:
home_spending[cols_keep]

,TIME_PERIOD,REF_AREA,Zone de référence,Dépense,OBS_VALUE,UNIT_MULT,CURRENCY
0,1995,FRA,France,Loisirs et culture,56302.000,6,EUR
1,1995,FRA,France,Produits alimentaires et boissons non alcoolisées,92535.000,6,EUR
2,1995,FRA,France,Total,643055.000,6,EUR
3,1995,FRA,France,"Meubles, articles de ménage et entretien coura...",36859.000,6,EUR
4,1995,FRA,France,Santé,24039.000,6,EUR
...,...,...,...,...,...,...,...
15222,2022,BGR,Bulgarie,Transports,7004.563,6,EUR
15223,2022,BGR,Bulgarie,Communications,2430.264,6,EUR
15224,2022,BGR,Bulgarie,Articles d'habillement et chaussures,1793.668,6,EUR
15225,2022,BGR,Bulgarie,Biens et services divers,3226.423,6,EUR
15226,2022,BGR,Bulgarie,"Logement, eau, gaz, électricité et autres comb...",9438.931,6,EUR

In [242]:
# 1. Lọc các cột bạn đã chọn
test = home_spending[cols_keep]

# 2. Đổi tên cột cho gọn & chuẩn
test = test.rename(columns={
    "TIME_PERIOD": "Year",
    "Zone de référence": "Country",
    "Dépense": "Expenditure_name",
    "OBS_VALUE": "value_raw",
    "UNIT_MULT": "Unit_mult",
    "CURRENCY": "Currency"
})

In [243]:
test["Expenditure_name"].unique()

array(['Loisirs et culture',
       'Produits alimentaires et boissons non alcoolisées', 'Total',
       'Meubles, articles de ménage et entretien courant du foyer',
       'Santé', 'Communications', 'Enseignement',
       'Boissons alcoolisées, tabac et stupéfiants',
       "Articles d'habillement et chaussures", 'Biens et services divers',
       'Logement, eau, gaz, électricité et autres combustibles',
       'Transports', 'Restaurants et hôtels'], dtype=object)

In [244]:
expenditure_map = {
    "Produits alimentaires et boissons non alcoolisées": "Food",
    "Loisirs et culture": "Recreation_Culture",
    "Meubles, articles de ménage et entretien courant du foyer": "Household_Goods",
    "Santé": "Health",
    "Communications": "Communication",
    "Enseignement": "Education",
    "Boissons alcoolisées, tabac et stupéfiants": "Alcohol_Tobacco",
    "Articles d'habillement et chaussures": "Clothing_Footwear",
    "Biens et services divers": "Other_Services",
    "Logement, eau, gaz, électricité et autres combustibles": "Housing_Utilities",
    "Transports": "Transport",
    "Restaurants et hôtels": "Restaurants_Hotels"
}


test["Expenditure_name"] = test["Expenditure_name"].replace(expenditure_map)

In [245]:
test["Expenditure_name"].unique()

array(['Recreation_Culture', 'Food', 'Total', 'Household_Goods', 'Health',
       'Communication', 'Education', 'Alcohol_Tobacco',
       'Clothing_Footwear', 'Other_Services', 'Housing_Utilities',
       'Transport', 'Restaurants_Hotels'], dtype=object)

In [246]:
total_df = (
    test[test["Expenditure_name"] == "Total"]
    [["Country", "Year", "value_raw"]]
    .rename(columns={"value_raw": "total_expenditure"})
)
detail_df = test[test["Expenditure_name"] != "Total"].copy()

detail_df = detail_df.merge(
    total_df,
    on=["Country", "Year"],
    how="left"
)
detail_df["Expenditure_Share %"] = (
    detail_df["value_raw"] / detail_df["total_expenditure"] * 100
)

In [247]:
detail_df["Expenditure_Share %"] = detail_df["Expenditure_Share %"].round(2)
detail_df

,Year,REF_AREA,Country,Expenditure_name,value_raw,Unit_mult,Currency,total_expenditure,Expenditure_Share %
0,1995,FRA,France,Recreation_Culture,56302.000,6,EUR,643055.000,8.76
1,1995,FRA,France,Food,92535.000,6,EUR,643055.000,14.39
2,1995,FRA,France,Household_Goods,36859.000,6,EUR,643055.000,5.73
3,1995,FRA,France,Health,24039.000,6,EUR,643055.000,3.74
4,1995,FRA,France,Communication,14504.000,6,EUR,643055.000,2.26
...,...,...,...,...,...,...,...,...,...
13945,2022,BGR,Bulgarie,Transport,7004.563,6,EUR,51215.238,13.68
13946,2022,BGR,Bulgarie,Communication,2430.264,6,EUR,51215.238,4.75
13947,2022,BGR,Bulgarie,Clothing_Footwear,1793.668,6,EUR,51215.238,3.50
13948,2022,BGR,Bulgarie,Other_Services,3226.423,6,EUR,51215.238,6.30
13949,2022,BGR,Bulgarie,Housing_Utilities,9438.931,6,EUR,51215.238,18.43

In [248]:
test = detail_df.drop(columns= ["total_expenditure"])

In [249]:
test = test.dropna(subset= ["value_raw","Expenditure_Share %"])

In [250]:
eu =test["REF_AREA"].isin(eu_regions["REF_AREA"])
test = test[eu]

In [251]:
test

,Year,REF_AREA,Country,Expenditure_name,value_raw,Unit_mult,Currency,Expenditure_Share %
0,1995,FRA,France,Recreation_Culture,56302.000,6,EUR,8.76
1,1995,FRA,France,Food,92535.000,6,EUR,14.39
2,1995,FRA,France,Household_Goods,36859.000,6,EUR,5.73
3,1995,FRA,France,Health,24039.000,6,EUR,3.74
4,1995,FRA,France,Communication,14504.000,6,EUR,2.26
...,...,...,...,...,...,...,...,...
13945,2022,BGR,Bulgarie,Transport,7004.563,6,EUR,13.68
13946,2022,BGR,Bulgarie,Communication,2430.264,6,EUR,4.75
13947,2022,BGR,Bulgarie,Clothing_Footwear,1793.668,6,EUR,3.50
13948,2022,BGR,Bulgarie,Other_Services,3226.423,6,EUR,6.30
13949,2022,BGR,Bulgarie,Housing_Utilities,9438.931,6,EUR,18.43

In [252]:
france = (test["REF_AREA"] == "FRA") & (test["Year"] == 1995)
test[france]

,Year,REF_AREA,Country,Expenditure_name,value_raw,Unit_mult,Currency,Expenditure_Share %
0,1995,FRA,France,Recreation_Culture,56302.0,6,EUR,8.76
1,1995,FRA,France,Food,92535.0,6,EUR,14.39
2,1995,FRA,France,Household_Goods,36859.0,6,EUR,5.73
3,1995,FRA,France,Health,24039.0,6,EUR,3.74
4,1995,FRA,France,Communication,14504.0,6,EUR,2.26
5,1995,FRA,France,Education,2321.0,6,EUR,0.36
6,1995,FRA,France,Alcohol_Tobacco,25084.0,6,EUR,3.90
7,1995,FRA,France,Clothing_Footwear,37808.0,6,EUR,5.88
8,1995,FRA,France,Other_Services,78785.0,6,EUR,12.25
9,1995,FRA,France,Housing_Utilities,150167.0,6,EUR,23.35
10,1995,FRA,France,Transport,92274.0,6,EUR,14.35
11,1995,FRA,France,Restaurants_Hotels,40500.0,6,EUR,6.30

In [253]:
# Số quốc gia và số nhóm chi tiêu chuẩn
N_country = test["Country"].nunique()
N_expenditure = test["Expenditure_name"].nunique()

In [254]:
countries_per_year = (
    test
    .groupby("Year")["Country"]
    .nunique()
    .reset_index(name="n_country")
)

countries_per_year["country_complete"] = (
    countries_per_year["n_country"] == N_country
)

In [255]:
expenditures_per_year = (
    test
    .groupby("Year")["Expenditure_name"]
    .nunique()
    .reset_index(name="n_expenditure")
)

expenditures_per_year["expenditure_complete"] = (
    expenditures_per_year["n_expenditure"] == N_expenditure
)

In [256]:
year_completeness = (
    countries_per_year
    .merge(expenditures_per_year, on="Year")
)
year_completeness

    Year  n_country  country_complete  n_expenditure  expenditure_complete
0   1995         28              True             12                  True
1   1996         28              True             12                  True
2   1997         28              True             12                  True
3   1998         28              True             12                  True
4   1999         28              True             12                  True
5   2000         28              True             12                  True
6   2001         28              True             12                  True
7   2002         28              True             12                  True
8   2003         28              True             12                  True
9   2004         28              True             12                  True
10  2005         28              True             12                  True
11  2006         28              True             12                  True
12  2007         28              True             12                  True
13  2008         28              True             12                  True
14  2009         28              True             12                  True
15  2010         28              True             12                  True
16  2011         28              True             12                  True
17  2012         28              True             12                  True
18  2013         28              True             12                  True
19  2014         28              True             12                  True
20  2015         28              True             12                  True
21  2016         28              True             12                  True
22  2017         28              True             12                  True
23  2018         28              True             12                  True
24  2019         28              True             12                  True
25  2020         28              True             12                  True
26  2021         28              True             12                  True
27  2022         28              True             12                  True
28  2023         12             False             12                  True

In [257]:
year = test["Year"] != "2023"
test = test[year]
test = test.reset_index(drop= True)

In [258]:
test.to_csv("C:/Downloads/data_clean/household_spending.csv",index= False)