In [408]:
import pandas as pd

In [409]:
tax = pd.read_csv(r"C:/Downloads/new_data/thuế lao động.csv")
eu_regions = pd.read_csv(r"C:/Downloads/new_data/eu_country.csv")
tax.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,REF_AREA,Zone de référence,MEASURE,Mesure,UNIT_MEASURE,Unité de mesure,...,OBS_VALUE,Valeur d'observation,DECIMALS,Décimales,UNIT_MULT,Multiplicateur d'unité,OBS_STATUS,Statut d'observation,CIVIL_STATUS,État civil
0,DATAFLOW,OECD.CTP.TPS:DSD_TAX_WAGES_COMP@DF_TW_COMP(2.1),Les impôts sur le travail - Indicateurs compar...,I,COL,Colombie,AV_RITEESSC,Taux moyen de l'impôt sur le revenu et des cot...,PT_WG_EARN_G,Pourcentage des salaires bruts,...,0.0,NaN,2,Two,0,Units,A,Valeur normale,M,Personne mariée
1,DATAFLOW,OECD.CTP.TPS:DSD_TAX_WAGES_COMP@DF_TW_COMP(2.1),Les impôts sur le travail - Indicateurs compar...,I,COL,Colombie,AV_RITEESSC,Taux moyen de l'impôt sur le revenu et des cot...,PT_WG_EARN_G,Pourcentage des salaires bruts,...,0.0,NaN,2,Two,0,Units,A,Valeur normale,M,Personne mariée
2,DATAFLOW,OECD.CTP.TPS:DSD_TAX_WAGES_COMP@DF_TW_COMP(2.1),Les impôts sur le travail - Indicateurs compar...,I,COL,Colombie,AV_RITEESSC,Taux moyen de l'impôt sur le revenu et des cot...,PT_WG_EARN_G,Pourcentage des salaires bruts,...,0.0,NaN,2,Two,0,Units,A,Valeur normale,M,Personne mariée
3,DATAFLOW,OECD.CTP.TPS:DSD_TAX_WAGES_COMP@DF_TW_COMP(2.1),Les impôts sur le travail - Indicateurs compar...,I,COL,Colombie,AV_RITEESSC,Taux moyen de l'impôt sur le revenu et des cot...,PT_WG_EARN_G,Pourcentage des salaires bruts,...,0.0,NaN,2,Two,0,Units,A,Valeur normale,M,Personne mariée
4,DATAFLOW,OECD.CTP.TPS:DSD_TAX_WAGES_COMP@DF_TW_COMP(2.1),Les impôts sur le travail - Indicateurs compar...,I,COL,Colombie,AV_RITEESSC,Taux moyen de l'impôt sur le revenu et des cot...,PT_WG_EARN_G,Pourcentage des salaires bruts,...,0.0,NaN,2,Two,0,Units,A,Valeur normale,M,Personne mariée

In [410]:
tax.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'ACTION', 'REF_AREA',
       'Zone de référence', 'MEASURE', 'Mesure', 'UNIT_MEASURE',
       'Unité de mesure', 'HOUSEHOLD_TYPE', 'Type de ménage',
       'INCOME_PRINCIPAL', 'Revenus du principal', 'INCOME_SPOUSE',
       'Revenus du conjoint', 'FREQ', 'Fréquence d'observation', 'TIME_PERIOD',
       'Période temporelle', 'OBS_VALUE', 'Valeur d'observation', 'DECIMALS',
       'Décimales', 'UNIT_MULT', 'Multiplicateur d'unité', 'OBS_STATUS',
       'Statut d'observation', 'CIVIL_STATUS', 'État civil'],
      dtype='object')

In [411]:
cols_keep = [
    "TIME_PERIOD",          
    "REF_AREA",             
    "Zone de référence",
    "Type de ménage",
    "Mesure",      
    "INCOME_PRINCIPAL", 
    "INCOME_SPOUSE",            
    "OBS_VALUE",   
    "UNIT_MEASURE",         
    # "UNIT_MULT",
]

In [412]:
tax[cols_keep]

,TIME_PERIOD,REF_AREA,Zone de référence,Type de ménage,Mesure,INCOME_PRINCIPAL,INCOME_SPOUSE,OBS_VALUE,UNIT_MEASURE
0,2000,COL,Colombie,"Couple, 2 children",Taux moyen de l'impôt sur le revenu et des cot...,AW100,AW100,0.0,PT_WG_EARN_G
1,2000,COL,Colombie,"Couple, 2 children",Taux moyen de l'impôt sur le revenu et des cot...,AW100,AW67,0.0,PT_WG_EARN_G
2,2000,COL,Colombie,"Couple, 2 children",Taux moyen de l'impôt sur le revenu et des cot...,AW100,NOEARN_UNEMP,0.0,PT_WG_EARN_G
3,2001,COL,Colombie,"Couple, 2 children",Taux moyen de l'impôt sur le revenu et des cot...,AW100,AW100,0.0,PT_WG_EARN_G
4,2001,COL,Colombie,"Couple, 2 children",Taux moyen de l'impôt sur le revenu et des cot...,AW100,AW67,0.0,PT_WG_EARN_G
...,...,...,...,...,...,...,...,...,...
119195,2024,COL,Colombie,"Single person, no children",Taux moyen des cotisations sociales obligatoir...,AW167,_Z,0.0,PT_WG_EARN_G
119196,2024,COL,Colombie,"Single person, no children",Taux moyen des cotisations patronales obligato...,AW167,_Z,0.0,PT_WG_EARN_G
119197,2024,COL,Colombie,"Single person, no children",Taux moyen net d'imposition à l'impôt sur le r...,AW167,_Z,0.0,PT_WG_EARN_G
119198,2024,COL,Colombie,"Single person, no children",Taux marginal net d'imposition du principal ap...,AW167,_Z,0.0,PT_WG_EARN_G
119199,2024,COL,Colombie,"Single person, no children",Taux moyen de l'impôt sur le revenu et des cot...,AW167,_Z,0.0,PT_WG_EARN_G

In [413]:
tax["Type de ménage"].unique()

array(['Couple, 2 children', 'Single person, no children',
       'Couple, no children', 'Single person, 2 children'], dtype=object)

In [414]:
# 1. Lọc các cột đã chọn
test = tax[cols_keep]

# 2. Đổi tên cột cho gọn & chuẩn
test = test.rename(columns={
    "TIME_PERIOD": "Year",
    "Zone de référence": "Country",
    "Mesure" : "Measure",
    "Type de ménage":"Household_type",
    "OBS_VALUE": "Value_tax",
    # "UNIT_MULT": "Unit_mult",
    "UNIT_MEASURE" : "Unit_measure"
})

In [415]:
eu_country = test["REF_AREA"].isin(eu_regions["REF_AREA"])
test = test[eu_country]
test

,Year,REF_AREA,Country,Household_type,Measure,INCOME_PRINCIPAL,INCOME_SPOUSE,Value_tax,Unit_measure
675,2000,DNK,Danemark,"Couple, 2 children",Taux moyen des cotisations patronales obligato...,AW100,AW100,0.0,PT_WG_EARN_G
676,2000,DNK,Danemark,"Couple, 2 children",Taux moyen des cotisations patronales obligato...,AW100,NOEARN_UNEMP,0.0,PT_WG_EARN_G
677,2000,DNK,Danemark,"Couple, 2 children",Taux moyen des cotisations patronales obligato...,AW100,AW67,0.0,PT_WG_EARN_G
678,2001,DNK,Danemark,"Couple, 2 children",Taux moyen des cotisations patronales obligato...,AW100,AW100,0.0,PT_WG_EARN_G
679,2001,DNK,Danemark,"Couple, 2 children",Taux moyen des cotisations patronales obligato...,AW100,NOEARN_UNEMP,0.0,PT_WG_EARN_G
...,...,...,...,...,...,...,...,...,...
118995,2022,DNK,Danemark,"Single person, no children",Taux moyen des cotisations sociales obligatoir...,AW167,_Z,0.0,PT_WG_EARN_G
118996,2023,DNK,Danemark,"Single person, no children",Taux moyen des cotisations sociales obligatoir...,AW167,_Z,0.0,PT_WG_EARN_G
118997,2024,DNK,Danemark,"Single person, no children",Taux moyen des cotisations sociales obligatoir...,AW167,_Z,0.0,PT_WG_EARN_G
118998,2000,EST,Estonie,"Single person, no children",Taux moyen des cotisations sociales obligatoir...,AW167,_Z,0.0,PT_WG_EARN_G
118999,2001,EST,Estonie,"Single person, no children",Taux moyen des cotisations sociales obligatoir...,AW167,_Z,0.0,PT_WG_EARN_G

In [416]:
test["Measure"].unique()

array(['Taux moyen des cotisations patronales obligatoires de sécurité sociale',
       'Taux moyen des cotisations sociales obligatoires des salariés',
       "Taux moyen de l'impôt sur le revenu",
       "Taux moyen de l'impôt sur le revenu et des cotisations salariales de sécurité sociale",
       "Taux marginal net d'imposition du principal apporteur de revenus",
       "Taux moyen net d'imposition à l'impôt sur le revenu",
       'Taux moyen du coin fiscal',
       'Coin fiscal marginal du principal apporteur de revenu',
       'Augmentation du revenu net après augmentation d’une unité monétaire des revenus bruts',
       'Augmentation du revenu net après augmentation d’une unité monétaire du coût brut de la main d’œuvre',
       "Coûts bruts de main-d'oeuvre avant impôts",
       'Revenus bruts avant impôts',
       'Revenus nets après impôts en monnaie nationale'], dtype=object)

In [417]:
measure_map = {
    # "Revenus bruts avant impôts": "income_before_tax",
    # "Revenus nets après impôts en monnaie nationale": "income_after_tax"
    "Taux moyen net d'imposition à l'impôt sur le revenu": "net_average_tax_rate"

}

test["Measure"]= test["Measure"].replace(measure_map)
test = test[test["Measure"].isin(measure_map.values())]
test = test[test["Unit_measure"] == "PT_WG_EARN_G"]
test = test.rename(
    columns={"Value_tax": "Net_average_tax_rate_pct"}
)

In [418]:
test["INCOME_PRINCIPAL"].unique()

array(['AW100', 'AW67', 'AW167'], dtype=object)

In [419]:
fra = test[(test["REF_AREA"] == "FRA") & (test["Year"] == 2024)]
fra

,Year,REF_AREA,Country,Household_type,Measure,INCOME_PRINCIPAL,INCOME_SPOUSE,Net_average_tax_rate_pct,Unit_measure
15299,2024,FRA,France,"Couple, 2 children",net_average_tax_rate,AW100,AW67,21.154450,PT_WG_EARN_G
16299,2024,FRA,France,"Couple, 2 children",net_average_tax_rate,AW100,AW100,24.137203,PT_WG_EARN_G
17299,2024,FRA,France,"Couple, 2 children",net_average_tax_rate,AW100,NOEARN_UNEMP,16.920236,PT_WG_EARN_G
58565,2024,FRA,France,"Single person, no children",net_average_tax_rate,AW100,_Z,28.052326,PT_WG_EARN_G
64899,2024,FRA,France,"Couple, no children",net_average_tax_rate,AW100,AW67,25.650068,PT_WG_EARN_G
88332,2024,FRA,France,"Single person, 2 children",net_average_tax_rate,AW67,_Z,-7.727297,PT_WG_EARN_G
94699,2024,FRA,France,"Single person, no children",net_average_tax_rate,AW67,_Z,23.747027,PT_WG_EARN_G
118203,2024,FRA,France,"Single person, no children",net_average_tax_rate,AW167,_Z,33.811097,PT_WG_EARN_G

In [420]:
income = test["INCOME_PRINCIPAL"] != "AW167"
test = test[income]
# No help
no_help = test["Net_average_tax_rate_pct"] > 0
test = test[no_help]

def convert(value) :
    return int(value[2:]) if value.startswith("AW") else 0

test["INCOME_SPOUSE"] = test["INCOME_SPOUSE"].apply(convert)
test["INCOME_PRINCIPAL"] = test["INCOME_PRINCIPAL"].apply(convert)


test["Net_average_tax_rate_pct"] = test["Net_average_tax_rate_pct"].round(2)
test[(test["REF_AREA"] == "FRA") & (test["Year"] == 2024)]

,Year,REF_AREA,Country,Household_type,Measure,INCOME_PRINCIPAL,INCOME_SPOUSE,Net_average_tax_rate_pct,Unit_measure
15299,2024,FRA,France,"Couple, 2 children",net_average_tax_rate,100,67,21.15,PT_WG_EARN_G
16299,2024,FRA,France,"Couple, 2 children",net_average_tax_rate,100,100,24.14,PT_WG_EARN_G
17299,2024,FRA,France,"Couple, 2 children",net_average_tax_rate,100,0,16.92,PT_WG_EARN_G
58565,2024,FRA,France,"Single person, no children",net_average_tax_rate,100,0,28.05,PT_WG_EARN_G
64899,2024,FRA,France,"Couple, no children",net_average_tax_rate,100,67,25.65,PT_WG_EARN_G
94699,2024,FRA,France,"Single person, no children",net_average_tax_rate,67,0,23.75,PT_WG_EARN_G

In [421]:
test = test.dropna(subset = ["Net_average_tax_rate_pct"])
test

,Year,REF_AREA,Country,Household_type,Measure,INCOME_PRINCIPAL,INCOME_SPOUSE,Net_average_tax_rate_pct,Unit_measure
15025,2000,AUT,Autriche,"Couple, 2 children",net_average_tax_rate,100,67,20.09,PT_WG_EARN_G
15026,2001,AUT,Autriche,"Couple, 2 children",net_average_tax_rate,100,67,20.74,PT_WG_EARN_G
15027,2002,AUT,Autriche,"Couple, 2 children",net_average_tax_rate,100,67,21.18,PT_WG_EARN_G
15028,2003,AUT,Autriche,"Couple, 2 children",net_average_tax_rate,100,67,21.66,PT_WG_EARN_G
15029,2004,AUT,Autriche,"Couple, 2 children",net_average_tax_rate,100,67,22.81,PT_WG_EARN_G
...,...,...,...,...,...,...,...,...,...
95320,2020,GBR,Royaume-Uni,"Single person, no children",net_average_tax_rate,67,0,18.41,PT_WG_EARN_G
95321,2021,GBR,Royaume-Uni,"Single person, no children",net_average_tax_rate,67,0,19.13,PT_WG_EARN_G
95322,2022,GBR,Royaume-Uni,"Single person, no children",net_average_tax_rate,67,0,19.39,PT_WG_EARN_G
95323,2023,GBR,Royaume-Uni,"Single person, no children",net_average_tax_rate,67,0,19.47,PT_WG_EARN_G
95324,2024,GBR,Royaume-Uni,"Single person, no children",net_average_tax_rate,67,0,17.76,PT_WG_EARN_G

In [422]:
test["Unit_measure"].unique()
test["Unit_measure"] = test["Unit_measure"].replace("PT_WG_EARN_G","PT")

In [423]:
couple = (test["INCOME_PRINCIPAL"] == 100) & (test["INCOME_SPOUSE"] == 67)
single = (test["INCOME_PRINCIPAL"] == 100) & (test["INCOME_SPOUSE"] == 0)
check = test[couple | single]

check.groupby("Year")[["Country","Household_type","Measure","INCOME_PRINCIPAL","INCOME_SPOUSE"]].nunique()

      Country  Household_type  Measure  INCOME_PRINCIPAL  INCOME_SPOUSE
Year
2000       25               3        1                 1              2
2001       25               3        1                 1              2
2002       25               3        1                 1              2
2003       25               3        1                 1              2
2004       25               3        1                 1              2
2005       25               3        1                 1              2
2006       25               3        1                 1              2
2007       25               3        1                 1              2
2008       25               3        1                 1              2
2009       25               3        1                 1              2
2010       25               3        1                 1              2
2011       25               3        1                 1              2
2012       25               3        1                 1              2
2013       25               3        1                 1              2
2014       25               3        1                 1              2
2015       25               3        1                 1              2
2016       25               3        1                 1              2
2017       25               3        1                 1              2
2018       25               3        1                 1              2
2019       25               3        1                 1              2
2020       25               3        1                 1              2
2021       25               3        1                 1              2
2022       25               3        1                 1              2
2023       25               3        1                 1              2
2024       25               3        1                 1              2

In [424]:
test = test.reset_index(drop = True)
test

,Year,REF_AREA,Country,Household_type,Measure,INCOME_PRINCIPAL,INCOME_SPOUSE,Net_average_tax_rate_pct,Unit_measure
0,2000,AUT,Autriche,"Couple, 2 children",net_average_tax_rate,100,67,20.09,PT
1,2001,AUT,Autriche,"Couple, 2 children",net_average_tax_rate,100,67,20.74,PT
2,2002,AUT,Autriche,"Couple, 2 children",net_average_tax_rate,100,67,21.18,PT
3,2003,AUT,Autriche,"Couple, 2 children",net_average_tax_rate,100,67,21.66,PT
4,2004,AUT,Autriche,"Couple, 2 children",net_average_tax_rate,100,67,22.81,PT
...,...,...,...,...,...,...,...,...,...
4213,2020,GBR,Royaume-Uni,"Single person, no children",net_average_tax_rate,67,0,18.41,PT
4214,2021,GBR,Royaume-Uni,"Single person, no children",net_average_tax_rate,67,0,19.13,PT
4215,2022,GBR,Royaume-Uni,"Single person, no children",net_average_tax_rate,67,0,19.39,PT
4216,2023,GBR,Royaume-Uni,"Single person, no children",net_average_tax_rate,67,0,19.47,PT
4217,2024,GBR,Royaume-Uni,"Single person, no children",net_average_tax_rate,67,0,17.76,PT

In [425]:
test.to_csv("C:/Downloads/data_clean/labour_tax.csv",index = False)